#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  pressSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl3,  encoder1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  encoder2,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           codedMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           gear,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int motorThreshhold = 32;

void setMotorFlashlight(int output) {
	motor(flashlight) = abs(output);
	motor(codedMotor) = output;
}

void motorLiveZone(int output) {
	if (output > 0) {
		if (output < motorThreshhold)
			setMotorFlashlight(motorThreshhold);
		else
			setMotorFlashlight(output);
	} else {
		if (output > -motorThreshhold)
			setMotorFlashlight(-motorThreshhold);
		else
			setMotorFlashlight(output);
	}
}

task main(){
	SensorValue(encoder2) = 0;
	SensorValue(encoder1) = 0;
	while(true) {
		int enc1 = SensorValue(encoder1);
		int enc2 = SensorValue(encoder2);
		if(abs(enc2 - enc1) < 20) {
			setMotorFlashlight(0);
		} else {
			motorLiveZone((enc1 - enc2)/8);
		}
	}
}
