#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  pressSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl3,  encoder1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  encoder2,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           codedMotor,    tmotorVex393_MC29, PIDControl, encoderPort, dgtl8)
#pragma config(Motor,  port9,           gear,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	SensorValue(encoder2) = 0;
	SensorValue(encoder1) = 0;
	nMotorPIDSpeedCtrl[codedMotor] = mtrPositionReg;
	mtrPid_kP = 0;
	mtrPid_kI = 0;
	mtrPid_kD = 0;
	while(true) {
		motor(codedMotor) = ;
	}
}
