#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  pressSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumper,         sensorTouch)
#pragma config(Sensor, dgtl3,  encoder1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar1,         sensorSONAR_cm)
#pragma config(Sensor, dgtl11, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           gear,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void setMotors(int leftOutput, int rightOutput, int flashlightOutput) {
			motor(leftWheel) = leftOutput;
		motor(rightWheel) = rightOutput;
		motor(flashlight) = flashlightOutput;
		}

task main(){
		waitUntil(SensorValue(sonar1) < 30);
		for (int i = 0; i < 4; i++) {
			setMotors(127,127,0);
			wait(0.5);
			setMotors(-127,-127,64);
			wait(0.5);
		}
		setMotors(0,0,0);

}
